Repository ImbueNetwork/imbue-frontend, pull requests merged in 2023-06, with the labels that each got.

#117 Verified Freelancers
  src/components/Briefs/BioInsights.tsx
  src/components/Dashboard/MyFreelancerApplications.tsx
  src/components/Freelancers/FreelancerFilter.tsx
  src/components/Profile/Clients.tsx
  src/db/knexfile.ts
  src/db/migrations/202201141340_initial.ts
  src/db/migrations/202204201410_create_project_properties_table.ts
  src/db/migrations/202210061410_create_brief.ts
  src/db/migrations/202210241002_milestone.ts
  src/db/migrations/202301071344_freelancers.ts
  src/db/migrations/202301161145_experience_and_scope_and_duration.ts
  src/db/migrations/202301171002_user_logins.ts
  src/db/migrations/202301301622_skills_and_industries.ts
  src/db/migrations/202301310120_clients_and_services_offered_and_languages.ts
  src/db/migrations/20230210132754_freelancer_ratings.ts
  src/db/migrations/20230601071352_verified-freelancers.ts
  src/model.ts
  src/pages/api/briefs/[id]/applications.ts
  src/pages/api/freelancers/index.ts
  src/pages/api/info/user.ts
  src/pages/api/models.ts
  src/pages/api/project/index.ts
  src/pages/briefs/[id].tsx
  src/pages/briefs/[id]/apply.tsx
  src/pages/freelancers/[slug].tsx
  src/pages/freelancers/index.tsx
  src/redux/services/freelancerService.ts
  src/styles/modules/freelancers.module.css
  src/types/freelancerTypes.ts
Labels: Size: Large

#135 fix: skeletons for freelancer loading
  src/components/Freelancers/FreelancersLoading.tsx
Labels: enhancement, good first issue, Size: XS

#146 added .env.example file
  .env.example
Labels: Size: XS, Priority: Low

#102 test suite for adding a new brief
  next.config.js
  package.json
  src/components/Login.tsx
  src/components/TagsInput.tsx
  src/config/index.ts
  src/pages/briefs/new.tsx
  tests/__mocks__/userData.ts
  tests/newBrief.test.tsx
Labels: Size: Large, Priority: High

#149 Swagger UI Integration
  .vscode/settings.json
  next.config.js
  package.json
  src/app/api-doc/ReactSwagger.tsx
  src/app/api-doc/page.tsx
  src/app/layout.tsx
  src/components/Application/ApplicationOwnerHeader.tsx
  src/db/index.ts
  src/lib/auth-cookies.ts
  src/lib/config.ts
  src/lib/models.ts
  src/lib/swagger.ts
  src/pages/api/auth/common.ts
  src/pages/api/auth/google/index.ts
  src/pages/api/auth/imbue.ts
  src/pages/api/auth/logout.ts
  src/pages/api/auth/register.ts
  src/pages/api/auth/web3/polkadot/index.ts
  src/pages/api/briefs/[id]/applications.ts
  src/pages/api/briefs/[id]/index.ts
  src/pages/api/briefs/[id]/status.ts
  src/pages/api/briefs/index.ts
  src/pages/api/briefs/save/[id].ts
  src/pages/api/briefs/save/index.ts
  src/pages/api/freelancers/[id]/applications.ts
  src/pages/api/freelancers/[id]/index.ts
  src/pages/api/freelancers/index.ts
  src/pages/api/freelancers/search.ts
  src/pages/api/info/index.ts
  src/pages/api/info/user.ts
  src/pages/api/project/[id].ts
  src/pages/api/project/index.ts
  src/pages/api/users/[...id].ts
  src/pages/api/users/[id]/applications/[applicationID].ts
  src/pages/api/users/[id]/briefs.ts
  src/pages/api/users/[id]/briefs/[briefID].ts
  src/pages/api/users/byid/[id].ts
  src/pages/api/users/byusernameoremail/[userOrEmail].ts
  src/pages/briefs/[id]/applications/index.tsx
  tsconfig.json
  yarn.lock
Labels: Size: Medium, Priority: Medium
